export { default as Header } from "./Header/Header.jsx";
export { default as Nav } from "./Nav/Nav.jsx";
export { default as About } from "./About/About.jsx";
export { default as Experience } from "./Experience/Experience.jsx";
export { default as Services } from "./Services/Services.jsx";
export { default as Portfolio } from "./Portfolio/Portfolio.jsx";
export { default as Testimonials } from "./Testimonials/Testimonials.jsx";
export { default as Contact } from "./Contact/Contact.jsx";
export { default as Footer } from "./Footer/Footer.jsx";
